debug: false

# 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon:
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    author: true
    # show readmore button
    readmore: auto # auto, always
  
  # 文章详情页面的文章卡片本体布局方案
  body:
    top_meta: [ author, category, date ]
    meta_library:
      author:
        avatar: https://pic.imgdb.cn/item/63a56d3108b68301634b34cc.jpg
        name: HDILP
        url: /about/
      # 文章创建日期
      date:
        icon: fas fa-calendar-alt
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fas fa-edit
        title: '更新于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fas fa-folder-open
      # 文章浏览计数
      counter:
        icon: fas fa-eye
        unit: '次浏览'
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag
# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
  logo: # choose [img] or [icon + title]
    img: ''
    icon: 
    title: 寒澈工作室
  menu:
    - name: 主页
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 时间线
      icon: fa-solid fa-archive
      url: archives/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/
  search:    # Search bar placeholder


    
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-envelope
      url: mailto:awm31415@163.com
    - icon: fab fa-github
      url: https://github.com/hdilp
  copyright: HDILP-STUDIO
  
plugins:
  scrollreveal:
    enable: true
    distance: 32px
    duration: 800 # ms
    interval: 20 # ms
    scale: 1 # 0.1~1
  parallax:
    enable: true
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 300000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images: # For personal use only. At your own risk if used for commercial purposes !!!
     - /picture/1.jpg
     - /picture/2.jpg
     - /picture/3.jpg
     - /picture/4.jpg
     - /picture/5.jpg
     - /picture/6.jpg
     - /picture/7.jpg
     - /picture/8.jpg
     - /picture/9.jpg
     - /picture/10.jpg
     - /picture/11.jpg
     - /picture/12.jpg
     - /picture/13.jpg
     - /picture/14.jpg
     - /picture/15.jpg


  aplayer:
    enable: true
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 4865548839    # song id / playlist id / album id / search keyword
    # Optional
    fixed: true      # enable fixed mode
    theme: '#FFAAB2'  # main color
    autoplay: true   # audio autoplay
    order: random       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.3       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true
    autoHide: true    # hide automaticaly
   
   pjax:
    enable: true
    # cover: false        # 封面是否pjax处理 false：每次切换页面封面都重载，适合封面较少的情况 true：封面经过Pjax处理，适合封面较多的情况
    # timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    # cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    # animation: false     # false, nprogress, circle
    #　banUrl:             # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/artitalk/'     # artitalk 不支持 pjax
      # - '/bb/'           # bbtalk 不支持 pjax
  
  message:
    enable: true
    icon: # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_style/_plugins/fontcolor.styl
      default: fa-solid fa-info-circle pink
      quection: fa-solid fa-question-circle pink
    time: # 默认持续时间
      default: 5000
      quection: 20000
    position: 'topRight'                 # 弹出位置 可选值：topRight, bottomRight, bottomLeft, topLeft, topCenter, bottomCenter, center
    transitionIn: 'bounceInLeft'         # 弹窗打开动画 可选值：bounceInLeft, bounceInRight, bounceInUp, bounceInDown, fadeIn, fadeInDown, fadeInUp, fadeInLeft, fadeInRight, flipInX
    transitionOut: 'fadeOutRight'        # 弹窗关闭动画 可选值：fadeOut, fadeOutUp, fadeOutDown, fadeOutLeft, fadeOutRight, flipOutX
    titleColor: 'var(--color-text)'      # 标题颜色
    messageColor: 'var(--color-text)'    # 消息颜色
    backgroundColor: 'var(--color-card)' # 默认背景色
    zindex: 2147483647                   # 层级
    copyright: # 是否在复制时弹出版权提示，影响范围：ctrl+c、代码块复制按钮、右键复制选项
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer: # 是否开启音乐通知；播放、暂停、失败 时的图标
      enable: true
      play: fa-solid fa-play
      pause: fa-solid fa-pause
    rightmenu:
      enable: true                        # 是否开启右键模块的消息通知
      notice: true                        # 唤醒原右键菜单的通知

cover:
  height_scheme: half # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display: 
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background:
  title: 'HDILP-STUDIO'
  subtitle: '寒澈工作室'
  search:  # search bar placeholder
#下面的icon和img二选一，icon使用fontawesome图标，img则使用图标外链
  features:

    


comments:
  title: <i class='fas fa-comments'></i> 评论区
  subtitle:
  service: twikoo
  # giscus
  # https://giscus.app
  # https://github.com/laymonage/giscus
  twikoo:
    path: # 全局评论地址
    # 其他配置项按照yml格式继续填写即可 除了 [el path] 选项
    envId: https://twikoo.hdilp.top/ # 腾讯云环境id
sidebar:
  for_page: [repos, qgroup, category, guide]
  for_post: [toc]
  widget_library:
    repos:
      class: text
      display: [ desktop, mobile ]
      header:
        icon: fa-solid fa-bullhorn
        title: 公告
        url:
      content:
        - '**本站已经完成从Github Page迁移到Vercel。**<br>国内访问速度从原来的55秒加速到5秒！'
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: true
      min_depth: 2
      max_depth: 5

    # 文档导航
    guide:
      class: grid
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-map-signs
        title: 分类导航
      fixed: true # 固定宽度
      rows:
        - name: 友情链接（未装修）
          icon: fa-solid fa-link
          url: /friends/
        - name: 说说&留言区
          icon: fa-solid fa-comment
          url: /shuoshuo/
        - name: 赞助
          icon: fa-solid fa-yen-sign
          url: /sponsorship/
        - name: GitHub主页
          icon: fa-brands fa-github
          url: https://www.github.com/HDILP/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: BiliBili主页
          icon: fa-brands fa-bilibili
          url: https://space.bilibili.com/544053960
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 主题更新日志
          icon: fa-solid fa-tags
          url: https://github.com/volantis-x/hexo-theme-volantis/releases/
          rel: external nofollow noopener noreferrer
          target: _blank

custom_css:
  scrollbar:
    size: 4px
    border: 2px
    color: '#2196f3'
    hover: '#ff5722'

pages:
  # 友链页面配置
  friends:
    layout_scheme: simple # simple: 简单布局, traditional: 传统布局

seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter



### 自定义右键 新
rightmenus:
  enable: true
  # 右键菜单项及加载顺序
  # 内容示例：plugins.[组名], menus.[组名], hr(分割线，推荐去线留白), music(音乐控制器)
  order:
    - plugins.navigation
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - plugins.elementCheck
    - plugins.elementImage
    - menus.link
    - hr
    - menus.darkMode
    - plugins.articlePage
    - music
    - menus.prevNext
  ############################
  # - {id: '', name: '', icon: '', link: '', event: '', group: ''}
  # id: 唯一值
  # name: 用于菜单名称显示
  # icon: 用于菜单图标显示
  # link: 跳转链接
  # event: 事件，当输入内容不为内置事件时，作 JavaScript 代码执行
  # group: 菜单项所处分组名称
  # 注：
  # 1. link/event 二选一，同时出现时仅处理 link
  # 2. 内置事件列表： copyText, copyLink, copyPaste, copyAll, copyCut, copyImg, printMode, readMode
  # 3. 内置组列表：navigation, inputBox, seletctText, elementCheck, elementImage, articlePage
  # 4. plugins 列允许自定义组内项目
  # 5. menus   列允许自定义组及其内容
  # 6. 除 navigation 外的内置组，在显示时会隐藏含 link 属性的菜单项
  ###########################
  # 基础项设置
  options:
    # 图标前缀 fa-solid, fa-regular, fa-light, fa-thin, fa-duotone, fa-brands
    iconPrefix: fa-solid
    # 例外，在 articlePage 组显示时（文章页）时依旧显示含 link 属性的菜单项
    articleShowLink: false
    # 当设定全局音乐播放器时，是否一直显示音乐控制菜单。false：仅当音乐播放时启用
    musicAlwaysShow: true
  # 右键内置组，预置实现
  plugins:
    # 导航组件
    # 横向排列，共用一行，仅显示图标 (原则上支持的数量不限)
    navigation:
      - { id: 'left', name: '转到上一页', icon: 'fa-solid fa-arrow-left pink', event: 'history.back()', group: 'navigation' }
      - { id: 'right', name: '转到下一页', icon: 'fa-solid fa-arrow-right pink', event: 'history.forward()', group: 'navigation' }
      - { id: 'redo', name: '刷新当前页面', icon: 'fa-solid fa-redo pink', event: 'window.location.reload()', group: 'navigation' }
      - { id: 'up', name: '回到顶部', icon: 'fa-solid fa-arrow-up pink', event: 'VolantisApp.scrolltoElement(volantis.dom.bodyAnchor)', group: 'navigation' }
      #- {id: 'home', name: '回到首页', icon: 'fa-solid fa-home', link: '/', group: 'navigation'}
    # 文本输入框相关组件
    # 生效于 input/textarea，粘贴、剪切、全选
    inputBox:
      - { id: 'copyPaste', name: '粘贴文本', icon: 'fa-solid fa-paste pink', event: 'copyPaste', group: 'inputBox' }
      - { id: 'copyAll', name: '全选文本', icon: 'fa-solid fa-object-ungroup pink', event: 'copyAll', group: 'inputBox' }
      - { id: 'copyCut', name: '剪切文本', icon: 'fa-solid fa-cut pink', event: 'copyCut', group: 'inputBox' }
    # 文本选中类组件
    # 生效于右键选中文本，__text__ 为选中的文本。
    seletctText:
      - { id: 'copyText', name: '复制文本', icon: 'fa-solid fa-copy pink', event: 'copyText', group: 'seletctText' }
      - { id: 'searchWord', name: '站内搜索', icon: 'fa-solid fa-search pink', event: 'OpenSearch(__text__)', group: 'seletctText' }
      - { id: 'bingSearch', name: '必应搜索', icon: 'fa-solid fa-search pink', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText' }
      #- {id: 'googleSearch', name: '谷歌搜索', icon: 'fa-solid fa-search', event: 'window.open(`https://www.google.com/search?q=${__text__}`)', group: 'seletctText'}
    # 链接判断组件
    # 生效于链接处的右键行为，__link__ 为链接地址
    elementCheck:
      - { id: 'openTab', name: '新标签页打开', icon: 'fa-solid fa-external-link-square-alt pink', event: 'window.open(__link__)', group: 'elementCheck' }
      - { id: 'copyLink', name: '复制链接地址', icon: 'fa-solid fa-link pink', event: 'copyLink', group: 'elementCheck' }
    # 图片判断类组件
    # 生效于图片类的右键行为，__link__ 为链接地址
    elementImage:
      - { id: 'copyImg', name: '复制图片', icon: 'fa-solid fa-image pink', event: 'copyImg', group: 'elementImage' }
      - { id: 'googleImg', name: '谷歌识图', icon: 'fa-solid fa-images pink', event: 'window.open(`https://www.google.com.hk/searchbyimage?image_url=${__link__}`)', group: 'elementImage' }
    # 文章页面组件
    # 生效于 post.article 页面
    articlePage:
      - { id: 'printMode', name: '打印页面', icon: 'fa-solid fa-print pink', event: 'printMode', group: 'articlePage' }
      - { id: 'readMode', name: '阅读模式', icon: 'fa-solid fa-book-open pink', event: 'readMode', group: 'articlePage' }
    # 右键自定义菜单区域
    menus:
      link:
        - { id: 'bilibili', name: 'BiliBili主页', icon: 'fa-brands fa-bilibili pink', link: 'https://space.bilibili.com/544053960', group: 'link' }
        - { id: 'sponsorship', name: '赞助', icon: 'fa-solid fa-yen-sign pink', link: 'https://hdilp-studio.ml/sponsorship', group: 'link' }
      darkMode:
        - { id: 'darkMode', name: '暗黑模式', icon: 'fa-solid fa-moon pink', event: 'volantis.dark.toggle()', group: 'darkMode' }
  ###

############################### Color Scheme ############################### > start
# Accessibility: 背景色和前景色要有足够的对比度 https://web.dev/color-contrast/
# https://ant.design/docs/spec/colors-cn
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#FFAAB2'
    # 链接色
    link: '#FFAAB2'
    # 按钮色
    button: '#FFAAB2'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: '#eeeeee'
    # 网站背景上的文字
    site_inner: '#f8bbd0'
    # 网站页脚文字
    site_footer: '#666'

    # 卡片背景色
    card: '#faf4f4'
    # 卡片上的普通文字
    text: '#444'

    # 区块和代码块背景色
    block: '#f6f6f6'
    # 代码块高亮时的背景色
    codeblock: '#FFF7EA'
    # 行内代码颜色
    inlinecode: '#c74f00'

    # 文章部分
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'

    # 列表文字
    list: '#666'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #000, 80)'
    # 辅助性文字
    meta: '#888'

    # 版权卡片背景色
    copyright_bkg: '#f5f5f5'
  # ------------


    # 夜间图片亮度
    brightness: 70%
############################### Color Scheme ############################### > end


############################### Open Graph ############################### > start
# https://ogp.me/
# https://hexo.io/zh-cn/docs/helpers#open-graph
open_graph:
  image: https://pic.imgdb.cn/item/63a56d3108b68301634b34cc.jpg
  twitter_card: summary # summary_large_image , summary
  #twitter_id:
  #twitter_site:
############################### Open Graph ############################### > end

# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: false
  
